baseurl = "/"
languageCode = "en-us"
title = "Go Where?"

[params]
  description = "A classic cocktail bar, the prefect place for you..."

[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 1
